table Equipment
	lineageTag: bec1b68d-11ce-44cf-bc5e-6cee6ec121ee

	column id
		dataType: string
		lineageTag: d4e17e14-d7ab-4ab0-80f8-e96e13f82db0
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: string
		lineageTag: aa28b48a-d667-470d-bf5a-b7854c57fe55
		summarizeBy: none
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column equipment_type_id
		dataType: string
		lineageTag: 70e3278f-a817-4ac3-8f36-60d26c4e5549
		summarizeBy: none
		sourceColumn: equipment_type_id

		annotation SummarizationSetBy = Automatic

	column equipment_location_id
		dataType: string
		lineageTag: 1e4fa981-4cdd-45dd-bd6b-bac8a7804e2e
		summarizeBy: none
		sourceColumn: equipment_location_id

		annotation SummarizationSetBy = Automatic

	column resource_id
		dataType: string
		lineageTag: 56912ce6-8db0-4786-8703-0d9829841b19
		summarizeBy: none
		sourceColumn: resource_id

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: ea7b3c9f-7b0f-417b-86d6-823c8eb6ad31
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: f2d17bcb-8dc1-48c2-8c70-90dcc0cacf4c
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column status
		dataType: int64
		formatString: 0
		lineageTag: ffea27d9-90ca-4bc3-8022-9d8f6dbbe149
		summarizeBy: sum
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column manufacturer_name
		dataType: string
		lineageTag: 2d8184c8-804d-480f-b846-e85db7e0d32f
		summarizeBy: none
		sourceColumn: manufacturer_name

		annotation SummarizationSetBy = Automatic

	column model_no
		dataType: string
		lineageTag: bf09692c-aa28-4a4b-a5bf-fb4c73f37d1b
		summarizeBy: none
		sourceColumn: model_no

		annotation SummarizationSetBy = Automatic

	column serial_no
		dataType: string
		lineageTag: d159e019-850b-43e2-b78a-66c0188c5580
		summarizeBy: none
		sourceColumn: serial_no

		annotation SummarizationSetBy = Automatic

	column date_created
		dataType: dateTime
		formatString: General Date
		lineageTag: 0d3d9541-88d5-45a0-9d18-6ac84e938afd
		summarizeBy: none
		sourceColumn: date_created

		variation Variation
			isDefault
			relationship: 62f60025-5cea-44ff-9a34-1a04ea166c0c
			defaultHierarchy: LocalDateTable_50dc7ade-76a4-46ac-96d6-11d314caf30c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column created_by_name
		dataType: string
		lineageTag: f548e838-1765-4980-87fe-5d7ca8cd010c
		summarizeBy: none
		sourceColumn: created_by_name

		annotation SummarizationSetBy = Automatic

	column date_last_updated
		dataType: dateTime
		formatString: General Date
		lineageTag: b3b0ad14-8da4-4848-ad4e-ceb45a9e0856
		summarizeBy: none
		sourceColumn: date_last_updated

		variation Variation
			isDefault
			relationship: 679d65fd-0dae-429a-bf53-bef0957a86ab
			defaultHierarchy: LocalDateTable_6c8f5e4a-3601-45b8-9f0a-d6252c4a4804.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column lastupdated_by_name
		dataType: string
		lineageTag: cdc959a7-2df5-40d9-97c3-f3b4699a0b23
		summarizeBy: none
		sourceColumn: lastupdated_by_name

		annotation SummarizationSetBy = Automatic

	column about_path
		dataType: string
		lineageTag: bcbb9868-b0db-41a4-a018-be60e06e59cb
		summarizeBy: none
		sourceColumn: about_path

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: string
		lineageTag: 82649839-5152-4926-a309-d485cb68f93a
		summarizeBy: none
		sourceColumn: organization_id

		annotation SummarizationSetBy = Automatic

	column date_active
		dataType: dateTime
		formatString: General Date
		lineageTag: c670feb8-73a7-4567-a5e3-fce5db965cc2
		summarizeBy: none
		sourceColumn: date_active

		variation Variation
			isDefault
			relationship: f353085e-0a7a-4876-aa9b-260f03758240
			defaultHierarchy: LocalDateTable_a7aa7c46-aa19-4dd9-b05e-c60380520d84.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column date_retired
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c27a5dd-258a-416b-961c-9949eaf1f768
		summarizeBy: none
		sourceColumn: date_retired

		variation Variation
			isDefault
			relationship: be00b91b-c940-4fd9-83d7-52efe05bf256
			defaultHierarchy: LocalDateTable_2841fdf8-900c-412d-902b-464b295c05c3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column date_offline
		dataType: dateTime
		formatString: General Date
		lineageTag: cffe72ea-4b0a-4c73-9f9e-e3e13872bce3
		summarizeBy: none
		sourceColumn: date_offline

		variation Variation
			isDefault
			relationship: 0a78117e-2a98-4420-8088-1a780ab7de33
			defaultHierarchy: LocalDateTable_7704b760-ef95-42f4-abd2-7d20b11c7cb2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column in_trash
		dataType: int64
		formatString: 0
		lineageTag: c92fed3a-57e3-4ec1-b3e6-7a30c1cb8341
		summarizeBy: sum
		sourceColumn: in_trash

		annotation SummarizationSetBy = Automatic

	column service_alert_message
		dataType: string
		lineageTag: 5fb5c53a-7509-4efc-ae79-3b80eead61d1
		summarizeBy: none
		sourceColumn: service_alert_message

		annotation SummarizationSetBy = Automatic

	column current_usage
		dataType: int64
		formatString: 0
		lineageTag: 2ccfea7f-a672-4323-9ecd-8b5c6c89e1e8
		summarizeBy: sum
		sourceColumn: current_usage

		annotation SummarizationSetBy = Automatic

	column status_code
		dataType: string
		lineageTag: 2464b296-2afc-4c49-a185-db9472b31fc2
		summarizeBy: none
		sourceColumn: status_code

		annotation SummarizationSetBy = Automatic

	column auto_recommend_maintenance
		dataType: int64
		formatString: 0
		lineageTag: 1354e017-433c-44ef-b6a1-2af211300da7
		summarizeBy: sum
		sourceColumn: auto_recommend_maintenance

		annotation SummarizationSetBy = Automatic

	column asset_tag
		dataType: string
		lineageTag: 61a18ccf-0765-4d2b-9626-d709857d38ca
		summarizeBy: none
		sourceColumn: asset_tag

		annotation SummarizationSetBy = Automatic

	column equipment_load_job_id
		dataType: string
		lineageTag: e3e1160c-3e1c-4a01-96c9-2ec493693b07
		summarizeBy: none
		sourceColumn: equipment_load_job_id

		annotation SummarizationSetBy = Automatic

	column no_of_equipment
		dataType: int64
		formatString: 0
		lineageTag: e8231dd4-a474-4453-b48a-d045c659ebd9
		summarizeBy: sum
		sourceColumn: no_of_equipment

		annotation SummarizationSetBy = Automatic

	column equipment_key
		dataType: int64
		formatString: 0
		lineageTag: 66dd838b-1c93-447e-9aeb-ad8c059c0539
		summarizeBy: sum
		sourceColumn: equipment_key

		annotation SummarizationSetBy = Automatic

	column verify_before_use
		dataType: int64
		formatString: 0
		lineageTag: 893f6022-08a4-4e08-8e39-cace13548441
		summarizeBy: sum
		sourceColumn: verify_before_use

		annotation SummarizationSetBy = Automatic

	column maintenance_schedule_state
		dataType: string
		lineageTag: fbab7ca0-1bf1-4a5d-8ac3-b6fa505506e3
		summarizeBy: none
		sourceColumn: maintenance_schedule_state

		annotation SummarizationSetBy = Automatic

	column calibration_category_id
		dataType: string
		lineageTag: aee63812-32f6-4a7c-be8b-a33f068389f1
		summarizeBy: none
		sourceColumn: calibration_category_id

		annotation SummarizationSetBy = Automatic

	column is_externally_managed
		dataType: int64
		formatString: 0
		lineageTag: d46e0e44-fced-47a3-a459-d446243af709
		summarizeBy: sum
		sourceColumn: is_externally_managed

		annotation SummarizationSetBy = Automatic

	column external_key
		dataType: string
		lineageTag: d4e15963-ef90-455d-8941-f6a81d4fb310
		summarizeBy: none
		sourceColumn: external_key

		annotation SummarizationSetBy = Automatic

	column requires_scan
		dataType: int64
		formatString: 0
		lineageTag: 2174ff74-4767-4e5c-8366-fde43b4a0c49
		summarizeBy: sum
		sourceColumn: requires_scan

		annotation SummarizationSetBy = Automatic

	column available_timesheet
		dataType: int64
		formatString: 0
		lineageTag: c6cc532e-f241-4df6-bfda-ee0fe5d79f83
		summarizeBy: sum
		sourceColumn: available_timesheet

		annotation SummarizationSetBy = Automatic

	column equipment_checkout_log_id
		dataType: string
		lineageTag: b4075080-0307-4399-9cd0-5795cd68e750
		summarizeBy: none
		sourceColumn: equipment_checkout_log_id

		annotation SummarizationSetBy = Automatic

	column date_of_purchase
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d5c3d42-59c7-4e35-b7df-1b3dbf7875dc
		summarizeBy: none
		sourceColumn: date_of_purchase

		variation Variation
			isDefault
			relationship: fb1203d5-8109-47ad-824e-69c7f5c06042
			defaultHierarchy: LocalDateTable_6439e354-75b9-46aa-9ca9-25aa9641b062.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column equipment_activation_rule_id
		dataType: string
		lineageTag: ce4058c9-052b-4333-b2ef-cb4090c56ffb
		summarizeBy: none
		sourceColumn: equipment_activation_rule_id

		annotation SummarizationSetBy = Automatic

	column equipment_checkout_rule_id
		dataType: string
		lineageTag: ec75c0c7-cc15-449b-a4d3-ff8ac8420720
		summarizeBy: none
		sourceColumn: equipment_checkout_rule_id

		annotation SummarizationSetBy = Automatic

	column equipment_checkin_rule_id
		dataType: string
		lineageTag: 58a4ad8b-2f60-49e5-9943-bde6911e4183
		summarizeBy: none
		sourceColumn: equipment_checkin_rule_id

		annotation SummarizationSetBy = Automatic

	column equipment_calibration_rule_id
		dataType: string
		lineageTag: f29c3c90-757e-4a92-8316-ae53ff54556c
		summarizeBy: none
		sourceColumn: equipment_calibration_rule_id

		annotation SummarizationSetBy = Automatic

	column site_share
		dataType: int64
		formatString: 0
		lineageTag: 38ec786e-b25e-4cb6-9615-1a540f7943ba
		summarizeBy: sum
		sourceColumn: site_share

		annotation SummarizationSetBy = Automatic

	column site_id
		dataType: string
		lineageTag: f9384f2a-8099-4ae0-85f5-36e288e5850d
		summarizeBy: none
		sourceColumn: site_id

		annotation SummarizationSetBy = Automatic

	column document_placeholder_template_group_id
		dataType: string
		lineageTag: 1a9387ee-08ba-470e-bb25-736588f10b9a
		summarizeBy: none
		sourceColumn: document_placeholder_template_group_id

		annotation SummarizationSetBy = Automatic

	column track_software_versions
		dataType: int64
		formatString: 0
		lineageTag: 190cf31a-ce5f-437a-b183-6318b7711778
		summarizeBy: sum
		sourceColumn: track_software_versions

		annotation SummarizationSetBy = Automatic

	column software_version
		dataType: string
		lineageTag: 1c316ae6-3468-428a-a711-bb6046593112
		summarizeBy: none
		sourceColumn: software_version

		annotation SummarizationSetBy = Automatic

	column date_last_service
		dataType: dateTime
		formatString: General Date
		lineageTag: 49f0f1b8-8cd9-4a3b-8e3d-3f7b0f5c28ff
		summarizeBy: none
		sourceColumn: date_last_service

		variation Variation
			isDefault
			relationship: 37dae091-986b-4096-9370-b20338184dad
			defaultHierarchy: LocalDateTable_25ad34fe-2bc8-4b05-9511-4db57530d7ec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column date_service_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 74239cbe-d3b5-469e-b046-a9852d9165a9
		summarizeBy: none
		sourceColumn: date_service_due

		variation Variation
			isDefault
			relationship: a49b71c3-2a66-410c-b477-3647295204f9
			defaultHierarchy: LocalDateTable_e3cf0a86-c0d3-45dc-b354-5fd40d1a318d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column site_equipment_key
		dataType: int64
		formatString: 0
		lineageTag: aabda760-d765-48ee-aa7a-16dc3914a4e2
		summarizeBy: sum
		sourceColumn: site_equipment_key

		annotation SummarizationSetBy = Automatic

	column ext_equipment_key
		dataType: int64
		formatString: 0
		lineageTag: 832fe880-7e72-414d-8627-96a9d3667453
		summarizeBy: sum
		sourceColumn: ext_equipment_key

		annotation SummarizationSetBy = Automatic

	column equipment_piece_type
		dataType: string
		lineageTag: cc24d134-c4d1-49da-b172-e8922338d2de
		summarizeBy: none
		sourceColumn: equipment_piece_type

		annotation SummarizationSetBy = Automatic

	column parent_equipment_id
		dataType: string
		lineageTag: c1c33d2c-d8da-4191-a5a4-96e4b056fa45
		summarizeBy: none
		sourceColumn: parent_equipment_id

		annotation SummarizationSetBy = Automatic

	column department_id
		dataType: string
		lineageTag: 6a9d567e-3f93-495d-80bf-a0a050d0e5e0
		summarizeBy: none
		sourceColumn: department_id

		annotation SummarizationSetBy = Automatic

	column transfer_site_id
		dataType: string
		lineageTag: b5e3bc2e-d008-4e39-9391-2a15e3504f9d
		summarizeBy: none
		sourceColumn: transfer_site_id

		annotation SummarizationSetBy = Automatic

	column transfer_type
		dataType: string
		lineageTag: 702f45fa-1239-4f37-8b3a-e103e526c9f5
		summarizeBy: none
		sourceColumn: transfer_type

		annotation SummarizationSetBy = Automatic

	column sub_status_code
		dataType: string
		lineageTag: 97aab252-bc6f-44c7-9b21-32aecfe1cd98
		summarizeBy: none
		sourceColumn: sub_status_code

		annotation SummarizationSetBy = Automatic

	partition Equipment = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId=getWorkspaceUUID ()]}[Data],
				    Dataflow = Workspace {[dataflowId=getDataflowUUID ("Equipment_DF_Test")]}[Data],
				    Equipment_ = Dataflow{[entity="Equipment",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Equipment_,{{"name_text", "Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

